apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-container
          image: saliibrahem/todo-list-node:44
          ports:
            - containerPort: 4000
          env:
           - name: MONGO_URI
             value: "mongodb://shrookali295:Shrook%40123@ac-uzybiwf-shard-00-00.1hkzuv6.mongodb.net:27017,ac-uzybiwf-shard-00-01.1hkzuv6.mongodb.net:27017,ac-uzybiwf-shard-00-02.1hkzuv6.mongodb.net:27017/?ssl=true&replicaSet=atlas-p9yfrs-shard-0&authSource=admin&retryWrites=true&w=majority"

