apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-container
          image: saliibrahem/todo-list-node:42
          ports:
            - containerPort: 4000
          env:
           - name: MONGO_URI
             value: "mongodb+srv://shrookali295:Shrook%40123@cluster0.1hkzuv6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

