apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://shrookali295:Shrook%40123@cluster0.ezp4ooc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
